[package]
name = "gauchos_vs_zombies"
version = "0.1.0"
edition = "2021"

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = "0.10.1"
bevy_asset_loader = "0.16.0"
bevy_ecs_tilemap = "0.10.0"
bevy_embedded_assets = "0.7.0"
bevy_rapier2d = "0.21.0"
noise = "0.8.2"
rand = "0.8.5"
