[package]
name = "gauchos_vs_zombies"
version = "0.1.0"
edition = "2021"

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = "0.9"
bevy_asset_loader = "0.14.1"
bevy_ecs_tilemap = "0.9.0"
bevy_embedded_assets = "0.6.2"
bevy_pixel_camera = "0.3.0"
rand = "0.8.5"
